.TH MIO_COMANDO 1 "18 Settembre 2025" "v1.0" "User Commands"
.SH NAME
mio_comando - esempio di comando
.SH SYNOPSIS
mio_comando [OPZIONI] FILE
.SH DESCRIPTION
Questo comando serve come esempio per creare una man page.
.SH OPTIONS
.TP
-h, --help
Mostra l'aiuto e termina.
.TP
-v, --version
Mostra la versione del programma.
.SH EXAMPLES
mio_comando -h
mio_comando file.txt
.SH AUTHOR
Stefano Ferri
